version: "3"
services:
  postgres:
    container_name: postgresMiit
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: miit
      PGDATA: /data/postgres
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  navigation:
    container_name: localtest
#    container_name: navigationService
    image: miitlocaltest:1.1
#    image: nawm77/miit-navigation:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/miit
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - MY_ARGS="hello world"
    deploy:
      resources:
        limits:
          cpus: '2'
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin